"""Description of the change

Revision ID: d41593c6b9ab
Revises: 
Create Date: 2024-06-11 07:26:49.417697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd41593c6b9ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_id', table_name='students')
    op.drop_index('ix_students_nis', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nis', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nama', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('jenis_kelamin', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('tempat_lahir', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.DATE(), nullable=True),
    sa.Column('agama', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('alamat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nama_ortu', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('no_telp', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('thn_ajaran', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thn_masuk', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('foto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('kd_kelas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_students_nis', 'students', ['nis'], unique=True)
    op.create_index('ix_students_id', 'students', ['id'], unique=False)
    # ### end Alembic commands ###
